application: miniedenprototype
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /tpl
  static_dir: tpl
  application_readable: true

- url: /img
  static_dir: img
  application_readable: true

- url: /css
  static_dir: css
  application_readable: true
  
- url: /fonts
  static_dir: fonts
  application_readable: true
  
- url: /js
  static_dir: js
  application_readable: true

- url: /.*
  script: main.app
  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest